version: '3.7'

services:

  db:
    image: postgres:14.1
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  rabbitmq:
    # https://hub.docker.com/_/rabbitmq/
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  chrome:
    image: selenium/node-chrome:4.1.1-20220121
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=15

  firefox:
    image: selenium/node-firefox:4.1.1-20220121
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=15


  selenium-hub:
    image: selenium/hub:4.1.1-20220121
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


  web_app:
    build: ./web_app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq